# Generated by Django 5.0.6 on 2026-03-08 05:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('regular', 'Regular Meeting'), ('emergency', 'Emergency Meeting'), ('planning', 'Planning Session'), ('review', 'Review Meeting'), ('general', 'General Assembly')], default='regular', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('is_virtual', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Google Meet link if virtual')),
                ('agenda', models.TextField()),
                ('minutes', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='meeting_attachments/')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='meeting_qrcodes/')),
                ('meeting_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('requires_attendance', models.BooleanField(default=True)),
                ('attendance_recorded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('executive', 'Student Executive'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('program_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('weekend', 'Weekend')], max_length=10, null=True)),
                ('year_of_admission', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400')], null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('requires_password_change', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('payment', 'Payment'), ('course_registration', 'Course Registration'), ('file_upload', 'File Upload'), ('admin_action', 'Admin Action'), ('executive_action', 'Executive Action'), ('meeting_created', 'Meeting Created')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('details', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('public_relations_officer', 'Public Relations Officer'), ('welfare_director', 'Welfare Director'), ('sports_director', 'Sports Director'), ('social_director', 'Social Director'), ('academic_director', 'Academic Director'), ('technical_director', 'Technical Director'), ('project_manager', 'Project Manager'), ('class_representative', 'Class Representative')], max_length=30)),
                ('executive_level', models.CharField(choices=[('departmental', 'Departmental Executive'), ('faculty', 'Faculty Executive'), ('institutional', 'Institutional Executive')], default='departmental', max_length=20)),
                ('tenure_start_date', models.DateField()),
                ('tenure_end_date', models.DateField()),
                ('tenure_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('resigned', 'Resigned'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('can_manage_events', models.BooleanField(default=True)),
                ('can_upload_materials', models.BooleanField(default=True)),
                ('can_send_announcements', models.BooleanField(default=True)),
                ('can_take_attendance', models.BooleanField(default=True)),
                ('can_manage_complaints', models.BooleanField(default=True)),
                ('can_view_financial_reports', models.BooleanField(default=False)),
                ('manifesto', models.TextField(blank=True, help_text="Executive's manifesto or vision")),
                ('achievements', models.TextField(blank=True, help_text='Achievements during tenure')),
                ('executive_image', models.ImageField(blank=True, help_text='Official executive portrait', null=True, upload_to='executives/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('official_email', models.EmailField(blank=True, help_text='Official executive email', max_length=254)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
                ('prefers_meeting_reminders', models.BooleanField(default=True)),
                ('meeting_reminder_time', models.IntegerField(default=60, help_text='Minutes before meeting to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_executive_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Executive',
                'verbose_name_plural': 'Student Executives',
                'ordering': ['-tenure_start_date', 'position'],
                'unique_together': {('user', 'tenure_start_date')},
            },
        ),
        migrations.CreateModel(
            name='ExecutiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_to_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.executivemeeting')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='accounts.studentexecutive')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='accounts.studentexecutive')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='organized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to='accounts.studentexecutive'),
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='accounts.studentexecutive'),
        ),
        migrations.CreateModel(
            name='ExecutiveDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_announcement', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='discussion_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='accounts.executivemeeting')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentexecutive')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='comment_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.executivediscussion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentexecutive')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_method', models.CharField(choices=[('qr_code', 'QR Code'), ('manual', 'Manual'), ('automatic', 'Automatic')], default='qr_code', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.executivemeeting')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='accounts.studentexecutive')),
            ],
            options={
                'unique_together': {('meeting', 'executive')},
            },
        ),
    ]
