# Generated by Django 5.0.6 on 2026-03-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_privacypolicy_termsofservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofservice',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='TermsOfService',
        ),
    ]
