# Generated by Django 5.0.6 on 2026-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
