# Generated by Django 5.0.6 on 2026-04-26 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_is_starred'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_archived'], name='messaging_m_is_arch_e2b586_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_draft'], name='messaging_m_is_draf_8d1988_idx'),
        ),
    ]
