# Generated by Django 5.0.6 on 2026-03-09 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_read_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_groups',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('all', 'All')], default='all', max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_messages', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('app_messages', models.BooleanField(default=True)),
                ('app_events', models.BooleanField(default=True)),
                ('app_payments', models.BooleanField(default=True)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('digest', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='never', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
