# Generated by Django 5.0.6 on 2026-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_announcement_target_groups_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach file to announcement', null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for announcement', null=True, upload_to='announcements/images/'),
        ),
    ]
