# Generated by Django 5.0.6 on 2026-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement_attachment_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
