# Generated by Django 5.0.6 on 2026-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
