# Generated by Django 5.0.6 on 2026-03-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
