# Generated by Django 5.0.6 on 2026-03-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_announcement_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this announcement was viewed'),
        ),
    ]
