# Generated by Django 5.0.6 on 2026-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_executiveteam_faq_partner_testimonial_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveteam',
            name='social_links',
        ),
        migrations.AddField(
            model_name='executiveteam',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook Profile URL'),
        ),
        migrations.AddField(
            model_name='executiveteam',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='executiveteam',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AddField(
            model_name='executiveteam',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter/X Profile URL'),
        ),
        migrations.AddField(
            model_name='executiveteam',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Personal Website'),
        ),
        migrations.AddField(
            model_name='executiveteam',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='WhatsApp Link'),
        ),
    ]
