# Generated by Django 5.0.6 on 2026-03-12 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_vlogreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VlogComment',
            new_name='VideoVlogComment',
        ),
        migrations.RenameModel(
            old_name='VlogReport',
            new_name='VideoVlogReport',
        ),
        migrations.RenameField(
            model_name='videovlogcomment',
            old_name='vlog',
            new_name='videovlog',
        ),
        migrations.RenameField(
            model_name='videovlogreport',
            old_name='vlog',
            new_name='videovlog',
        ),
    ]
