# Generated by Django 5.0.6 on 2026-03-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_vlogcomment_videovlogcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovlogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.videovlogcomment'),
        ),
    ]
