# Generated by Django 5.0.6 on 2026-04-26 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_blogcomment_options_blogpost_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVlogCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.videovlogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VideoVlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_likes', to=settings.AUTH_USER_MODEL)),
                ('videovlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.videovlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('videovlog', 'user')},
            },
        ),
    ]
