# Generated by Django 5.0.6 on 2026-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
