# Generated by Django 5.0.6 on 2026-03-14 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentidcard',
            options={'verbose_name': 'Student ID Card', 'verbose_name_plural': 'Student ID Cards'},
        ),
        migrations.RenameField(
            model_name='studentidcard',
            old_name='generated_at',
            new_name='issued_at',
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='allergies',
            field=models.TextField(blank=True, help_text='Any known allergies', null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='emergency_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Important medical conditions', null=True),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='valid_until',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
        ),
    ]
