# Generated by Django 5.0.6 on 2026-03-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_studentidcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentidcard',
            name='student_signature',
            field=models.ImageField(blank=True, help_text="Upload student's signature (PNG with transparent background recommended)", null=True, upload_to='signatures/'),
        ),
    ]
