# Generated by Django 5.0.6 on 2026-03-16 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_studentidcard_student_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('registration', 'Registration'), ('examination', 'Examination'), ('holiday', 'Holiday'), ('event', 'Event'), ('deadline', 'Deadline')], default='academic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester')], null=True)),
                ('level', models.IntegerField(choices=[(100, 'All Levels'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400')], default=100)),
                ('venue', models.CharField(blank=True, help_text='Location if applicable', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Calendar Event',
                'verbose_name_plural': 'Academic Calendar Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.CharField(help_text='e.g., BTML201', max_length=20)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400')])),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester')])),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('exam_year', models.IntegerField(help_text='Year the exam was taken')),
                ('file', models.FileField(upload_to='past_questions/')),
                ('file_size', models.IntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloads', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_past_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Past Question',
                'verbose_name_plural': 'Past Questions',
                'ordering': ['-exam_year', 'level', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='StudentHandbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(help_text='e.g., 2024 Edition', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='handbooks/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='handbook_covers/')),
                ('file_size', models.IntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloads', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current handbook?')),
                ('effective_date', models.DateField(help_text='Date from which this handbook is effective')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_handbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Handbook',
                'verbose_name_plural': 'Student Handbooks',
                'ordering': ['-effective_date'],
            },
        ),
    ]
